### ISSUE TITLE
Support multiple keys

### ISSUE THREAD

**Issue by J-Rojas** [lupas/vue-keypress#6]
Hi, I think this is a useful tool, but it sorely lacks the ability to monitor multiple key events.

I don't think it would be efficient to use multiple component instances for this purpose. Would you accept a PR for this adjustment?

**Comment by lupas** [comment]
Hey @J-Rojas 
That would be a great addition to the module, so a PR is very welcome!

Thanks for the suggestion!

**Comment by J-Rojas** [comment]
Ok, I have it working BUT I did have to change the API significantly to make it work for my use case. 

I needed to have two key codes work with two different modifier keys. With the current API, I would have had to register 4 keypress objects for this to work. So I changed the API to use a configuration object for this purpose. This allows for maximum flexibility with only one configuration. It will generate two global window key handlers instead of 4.

Let me know if this is something you would consider and I'll submit the PR.  
    
    <Keypress :config="keyEvents" @pressed="onKeyPressed" />

    keyEvents: [{
      keyCodes: [37, 39],
      events: ['keyup'],
      modifiers: [['altKey'], ['altKey']]
    },
    {
      keyCodes: [37, 39],
      events: ['keyup'],
      modifiers: [['shiftKey'], ['shiftKey']]
    }]

    onKeyPressed(keyCode, keyEvent, keyModifiers) {
      if (keyModifiers.indexOf('altKey') != -1) {
        switch (keyCode) {
          case 37:            
              this.onBackStep()            
              this.onSkipToBeginning()       
            break;
          case 39:
              this.onForwardStep()
              this.onSkipToEnd()            
            break;
        }
      } else if (keyModifiers.indexOf('shiftKey') != -1) {
        switch (keyCode) {
          case 37:                          
              this.onSkipToBeginning()       
            break;
          case 39:              
              this.onSkipToEnd()            
            break;
        }
      }
    }

**Comment by J-Rojas** [comment]
Alternatively, this could also be done if a simpler event handling is desired. It will also generate 2 global window event handlers instead of 4, but you can rely on the modifiers to have already been reliably filtered when the v-on events handlers are triggered.

    <Keypress :config="keyEventsAlt" @pressed="onKeyPressedAlt" />
    <Keypress :config="keyEventsShift" @pressed="onKeyPressedShift" />

    keyEventsAlt: [{
      keyCodes: [37, 39],
      events: ['keyup'],
      modifiers: ['altKey']
    }],
    keyEventsShift: [{
      keyCodes: [37, 39],
      events: ['keyup'],
      modifiers: ['shiftKey']
    }]

    onKeyPressedAlt(keyCode) {
      switch (keyCode) {
        case 37:
          ...
          break;
        case 39:
           ...
          break;
      }
    }   

    onKeyPressedShift(keyCode) {
      switch (keyCode) {
        case 37:
          ...
        break;
       case 39:
        ...
        break;
      }
    }

**Comment by lupas** [comment]
@J-Rojas 
You only show the parents code here, could you provide the code you actually changed within the component? If the change is significant we could also opt for providing a second component <Keypress-Multiple/> rather than packing all special cases in the existing one, so the user has the choice.

I'd like to keep the module as simple as possible and not add complexity if not needed. 9/10 users need only one key, so making the props more cumbersome for these 9 is not what I want to do..

**Comment by J-Rojas** [comment]
I sent the PR. I can answer any implementation questions that you have. Having a multikeypress component sounds like a good balance.

**Comment by lupas** [comment]
Hey @J-Rojas 

I merged your PR but did a bunch of changes on top before publishing [v2.0.0](https://github.com/lupas/vue-keypress/releases/tag/v2.0.0).

As mentioned earlier I'd like the API to be as simple as possible, and the way I implemented now is imho the easiest to understand.

Have a look at the updated README, it should explain it quite well. Take into account the updated naming of some props & events.

Hope that is working for your case, otherwise just keep on using your branch. Also, a pure JS implementation would probably even be much better, so let me know if you start working in that.

In any case, thanks a lot for your help on this, really appreciate it!
